### ISSUE TITLE
xcode benchmark

### ISSUE THREAD

**Issue by viplike** [tarkh/hackintosh#1]
привет, можешь пжл замерить за сколько у тебя соберется проект на xcode, очень интересная сборка у тебя. 

https://github.com/devMEremenko/XcodeBenchmark

**Comment by tarkh** [comment]
Привет!
Только руки дошли установить XCode и протестировать:
<p align="center" width="100%">
<img src="https://github.com/tarkh/hackintosh/raw/macOS-12-(Monterey)/Huananzhi-F8D/benchmarks/xcode.png?raw=true">
</p>
