### ISSUE TITLE
Enable ReleaseUsbOwnership

### ISSUE THREAD

**Issue by Schaka** [tarkh/hackintosh#3]
Currently, when using a GPU that has both a Legacy and UEFI BIOS, it's not possible to boot while completely disabling CSM. 
When disabling CSM completely, there is no POST, as no VGA output can be found.

When enabling UEFI in all regards (except keeping VGA at Legacy), MacOS doesn't boot but instead crashes because it loses access to the USB drive. Enabling the above property therefore allows to use "hybrid" GPUs like the RX 560, 570 and 580.

Tested with my Sapphre RX 560D 2GB.

**Comment by tarkh** [comment]
Thank you for this details, I will test them and push to upstream.

**Comment by Schaka** [comment]
Double check if it messes with your USB map. Things seemed fine for me, but you never know how many revisions of the Chinese boards there really are.
