### ISSUE TITLE
Low geekbench 5 score

### ISSUE THREAD

**Issue by huan-nba** [tarkh/hackintosh#6]
Hi tarkh, 
I'm getting very low geekbench5  on the exact system. Everything in the guide was followed.
My score it 8xx for single and around 8700 for multicore where it should be 14xxx
My cinebench r23 score seems fine btw.
I also get low score on my windows installation too
side note: I'm using 32gb 2133 ddr 2x16 gb stick, 1 per cpu. 
Thank you

**Comment by huan-nba** [comment]
@tarkh hi, any idea on top of your mind?

**Comment by tarkh** [comment]
@huan-nba Hi! Each CPU have 4 dedicated RAM channels, so 8 for double-socket. You utilize only 2, so it's possible that this is the reason of low benchmark results. Results in my guide made on system, that utilize all 8 memory slots.
