### ISSUE TITLE
Expect the boss to adapt to the MAC13 system, do you have a plan? 

### ISSUE THREAD

**Issue by itq5** [tarkh/hackintosh#8]
Expect the boss to adapt to the MAC13 system, do you have a plan?

**Comment by tarkh** [comment]
Updated to macOS 14 Sonoma: https://github.com/tarkh/hackintosh/tree/main/Huananzhi-F8D

**Comment by itq5** [comment]
Update to macOS 14 Sonoma: https://github.com/tarkh/hackintosh/tree/main/Huananzhi-F8D

Thank you for the update
